######################################################################
# Automatically generated by qmake (3.0) Thu Dec 17 21:42:21 2015
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += . src/include ../arduino-serial

DESTDIR = bin/
OBJECTS_DIR = bin/

# Input
QT += gui widgets core
SOURCES += src/*.cpp
