


















.build_ano/megaADK/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build_ano/megaADK/arduino/wiring_digital.d

.build_ano/megaADK/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build_ano/megaADK/arduino/WInterrupts.d

.build_ano/megaADK/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build_ano/megaADK/arduino/wiring_shift.d

.build_ano/megaADK/arduino/wiring.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build_ano/megaADK/arduino/wiring.d

.build_ano/megaADK/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build_ano/megaADK/arduino/wiring_analog.d

.build_ano/megaADK/arduino/hooks.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo [93marduino/hooks.c[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build_ano/megaADK/arduino/hooks.d

.build_ano/megaADK/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build_ano/megaADK/arduino/wiring_pulse.d






.build_ano/megaADK/arduino/HardwareSerial0.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo [93marduino/HardwareSerial0.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build_ano/megaADK/arduino/HardwareSerial0.d

.build_ano/megaADK/arduino/HID.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
include .build_ano/megaADK/arduino/HID.d

.build_ano/megaADK/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build_ano/megaADK/arduino/USBCore.d

.build_ano/megaADK/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build_ano/megaADK/arduino/HardwareSerial.d

.build_ano/megaADK/arduino/main.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build_ano/megaADK/arduino/main.d

.build_ano/megaADK/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build_ano/megaADK/arduino/IPAddress.d

.build_ano/megaADK/arduino/Print.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build_ano/megaADK/arduino/Print.d

.build_ano/megaADK/arduino/Tone.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build_ano/megaADK/arduino/Tone.d

.build_ano/megaADK/arduino/HardwareSerial3.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo [93marduino/HardwareSerial3.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build_ano/megaADK/arduino/HardwareSerial3.d

.build_ano/megaADK/arduino/HardwareSerial2.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo [93marduino/HardwareSerial2.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build_ano/megaADK/arduino/HardwareSerial2.d

.build_ano/megaADK/arduino/HardwareSerial1.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo [93marduino/HardwareSerial1.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build_ano/megaADK/arduino/HardwareSerial1.d

.build_ano/megaADK/arduino/WMath.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build_ano/megaADK/arduino/WMath.d

.build_ano/megaADK/arduino/Stream.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build_ano/megaADK/arduino/Stream.d

.build_ano/megaADK/arduino/new.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build_ano/megaADK/arduino/new.d

.build_ano/megaADK/arduino/WString.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build_ano/megaADK/arduino/WString.d

.build_ano/megaADK/arduino/abi.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo [93marduino/abi.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build_ano/megaADK/arduino/abi.d

.build_ano/megaADK/arduino/CDC.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build_ano/megaADK/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build_ano/megaADK/arduino/CDC.d



.build_ano/megaADK/arduino/libarduino.a : .build_ano/megaADK/arduino/wiring_digital.o .build_ano/megaADK/arduino/WInterrupts.o .build_ano/megaADK/arduino/wiring_shift.o .build_ano/megaADK/arduino/wiring.o .build_ano/megaADK/arduino/wiring_analog.o .build_ano/megaADK/arduino/hooks.o .build_ano/megaADK/arduino/wiring_pulse.o .build_ano/megaADK/arduino/HardwareSerial0.o .build_ano/megaADK/arduino/HID.o .build_ano/megaADK/arduino/USBCore.o .build_ano/megaADK/arduino/HardwareSerial.o .build_ano/megaADK/arduino/main.o .build_ano/megaADK/arduino/IPAddress.o .build_ano/megaADK/arduino/Print.o .build_ano/megaADK/arduino/Tone.o .build_ano/megaADK/arduino/HardwareSerial3.o .build_ano/megaADK/arduino/HardwareSerial2.o .build_ano/megaADK/arduino/HardwareSerial1.o .build_ano/megaADK/arduino/WMath.o .build_ano/megaADK/arduino/Stream.o .build_ano/megaADK/arduino/new.o .build_ano/megaADK/arduino/WString.o .build_ano/megaADK/arduino/abi.o .build_ano/megaADK/arduino/CDC.o
	@echo [92mLinking libarduino.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build_ano/megaADK/src/coffee_machine.o : src/coffee_machine.cpp
	@echo [93msrc/coffee_machine.cpp[0m
	@mkdir -p .build_ano/megaADK/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/mega -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c src/coffee_machine.cpp
include .build_ano/megaADK/src/coffee_machine.d







.build_ano/megaADK/firmware.elf : .build_ano/megaADK/src/coffee_machine.o .build_ano/megaADK/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build_ano/megaADK/firmware.hex : .build_ano/megaADK/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build_ano/megaADK/src/dependencies.d .build_ano/megaADK/arduino/dependencies.d

all : .build_ano/megaADK/firmware.hex
	@true

