######################################################################
# Automatically generated by qmake (3.0) Mon Dec 14 22:39:14 2015
######################################################################

TEMPLATE = app
TARGET = gui_src
INCLUDEPATH += .

QT += gui declarative widgets
# Input
SOURCES += app.cpp
